name: lolaricci
favicon: null
layout_spectrum: 1
typography_spectrum: 0.11944
title: Lola Ricci · custom cookies
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f85257'
    - '#9c9c9c'
    - '#ff0000'
    - '#ffffff'
    - '#000000'
  brandStrength: 0
  lightness: 0.6875
  saturation: 0.75
  rhythmicContrast: 0.25
purpose: []
